language: node_js
sudo: required
python:
  - "3.6"
node_js:
  - "node"
dist: trusty
addons:
  chrome: stable
before_install:
  - wget https://chromedriver.storage.googleapis.com/2.35/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip -d test/driver/
install:
  - python3 -m pip install selenium
  - npm install
  - npm install -g grunt-cli
  - grunt chrome
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
script:
  - cd test
  - python3 ./test_main.py
